name: Spell checking

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check spelling
        uses: check-spelling/check-spelling@0.0.16-alpha
